if [ ! -f "./version.h" ]; then
    echo "// This file was automatically generated by shs" > ./version.h
    echo "#pragma once" >> ./version.h
    echo "namespace shs {" >> ./version.h
    echo "extern const char kShsVersion[];" >> ./version.h
    echo "extern const char kCompiler[];" >> ./version.h
    echo "extern const char kPlatform[];" >> ./version.h
    echo "extern const char kBuilderName[];" >> ./version.h
    echo "} // namespace shs" >> ./version.h
fi

echo "// This file was automatically generated by shs" > ./version.cc.tmp
echo "#include \"version.h\"" >> ./version.cc.tmp
echo "namespace shs {" >> ./version.cc.tmp
echo "const char kShsVersion[] = \"`grep ^VERSION= ../Makefile | cut -d "=" -f2`\";" >> ./version.cc.tmp
echo "const char kCompiler[] = \"$1\";" >> ./version.cc.tmp
echo "const char kPlatform[] = \"$2\";" >> ./version.cc.tmp
echo "const char kBuilderName[] = \"`echo $USER`\";" >> ./version.cc.tmp
echo "} // namespace shs" >> ./version.cc.tmp

if [ ! -f "./version.cc" ]; then
    mv version.cc.tmp version.cc
    exit 0
fi

cmp --silent version.cc version.cc.tmp || cp version.cc.tmp version.cc
rm -f version.cc.tmp
